version: "3"

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    command: npm start
    volumes:
      - .:/usr/app
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - c:/users/enzor/postgres/data:/var/lib/postgresql/data